using System;
using System.Collections.Generic;
using System.Text;

namespace Domain_Layer.DbModels.Enum
{
    public enum CrimeType
    {
        Unknown = 0,
        HitAndRun,
        LarcenyFromMV,
        Shoplifting,
        LarcenyOfBicycle,
        Forgery,
        MalDestProperty,
        WarrantArrest,
        LarcenyFromResidence,
        SimpleAssault,
        LarcenyFromBuilding,
        Housebreak,
        Accident,
        AdminError,
        LarcenyFromPerson,
        Threats,
        AggravatedAssault,
        FlimFlam,
        MissingPerson,
        AutoTheft,
        Harassment,
        StreetRobbery,
        Drugs,
        SuspiciousPackage,
        CommercialBreak,
        Trespassing,
        LarcenyMisc,
        OUI,
        PhoneCalls,
        Disorderly,
        LarcenyOfPlate,
        IndecentExposure,
        CommercialRobbery,
        TaxiViolation,
        DrinkingInPublic,
        RecStolenProperty,
        ViolationOfHO,
        LarcenyOfServices,
        Counterfeiting,
        ExtortionBlackmail,
        WeaponViolations,
        NoiseComplaint,
        Medical,
        AnnoyingAccosting,
        Embezzlement,
        Arson,
        CivilDispute,
        SexOffenderViolation,
        PeepingSpying,
        LiquorPossessionSale,
        Prostitution,
        ElderAssistance,
        Stalking,
        Encampment,
        Kidnapping,
        Homicide,
        ViolationOfRO,
        DomesticDispute,
        Gambling,
        Hoarding
    }
}
